spring:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:testdb
    password:
    driver-class-name: org.h2.Driver
    username: sa
  port: 8080
